// Ticker lists only. All financial data (pe, eps, marketCap, beta, dividendYield, prices)
// is fetched live from the /stats and /simulate lambda endpoints.

export const STOCKS_DATA = {
  tech: [
    { ticker: 'AAPL', name: 'Apple Inc.' },
    { ticker: 'MSFT', name: 'Microsoft' },
    { ticker: 'GOOGL', name: 'Alphabet' },
    { ticker: 'AMZN', name: 'Amazon' },
    { ticker: 'META', name: 'Meta Platforms' },
    { ticker: 'NVDA', name: 'NVIDIA' },
    { ticker: 'TSLA', name: 'Tesla' },
    { ticker: 'ADBE', name: 'Adobe' },
    { ticker: 'CRM', name: 'Salesforce' },
    { ticker: 'INTC', name: 'Intel' },
    { ticker: 'AMD', name: 'AMD' },
    { ticker: 'ORCL', name: 'Oracle' },
    { ticker: 'IBM', name: 'IBM' },
    { ticker: 'CSCO', name: 'Cisco Systems' },
    { ticker: 'QCOM', name: 'Qualcomm' },
    { ticker: 'TXN', name: 'Texas Instruments' },
    { ticker: 'AVGO', name: 'Broadcom' },
    { ticker: 'NOW', name: 'ServiceNow' },
    { ticker: 'INTU', name: 'Intuit' },
    { ticker: 'AMAT', name: 'Applied Materials' },
  ],
  healthcare: [
    { ticker: 'JNJ', name: 'Johnson & Johnson' },
    { ticker: 'UNH', name: 'UnitedHealth' },
    { ticker: 'PFE', name: 'Pfizer' },
    { ticker: 'ABBV', name: 'AbbVie' },
    { ticker: 'MRK', name: 'Merck' },
    { ticker: 'TMO', name: 'Thermo Fisher' },
    { ticker: 'LLY', name: 'Eli Lilly' },
    { ticker: 'ABT', name: 'Abbott Labs' },
    { ticker: 'BMY', name: 'Bristol-Myers' },
    { ticker: 'AMGN', name: 'Amgen' },
    { ticker: 'GILD', name: 'Gilead Sciences' },
    { ticker: 'CVS', name: 'CVS Health' },
    { ticker: 'ISRG', name: 'Intuitive Surgical' },
    { ticker: 'VRTX', name: 'Vertex Pharma' },
    { ticker: 'MDT', name: 'Medtronic' },
    { ticker: 'CI', name: 'Cigna' },
    { ticker: 'DHR', name: 'Danaher' },
    { ticker: 'ZTS', name: 'Zoetis' },
    { ticker: 'SYK', name: 'Stryker' },
    { ticker: 'HUM', name: 'Humana' },
  ],
  finance: [
    { ticker: 'JPM', name: 'JPMorgan Chase' },
    { ticker: 'BAC', name: 'Bank of America' },
    { ticker: 'WFC', name: 'Wells Fargo' },
    { ticker: 'GS', name: 'Goldman Sachs' },
    { ticker: 'MS', name: 'Morgan Stanley' },
    { ticker: 'C', name: 'Citigroup' },
    { ticker: 'V', name: 'Visa Inc.' },
    { ticker: 'MA', name: 'Mastercard' },
    { ticker: 'AXP', name: 'American Express' },
    { ticker: 'BLK', name: 'BlackRock' },
    { ticker: 'SCHW', name: 'Charles Schwab' },
    { ticker: 'CB', name: 'Chubb Ltd' },
    { ticker: 'MMC', name: 'Marsh McLennan' },
    { ticker: 'PNC', name: 'PNC Financial' },
    { ticker: 'USB', name: 'U.S. Bancorp' },
    { ticker: 'TFC', name: 'Truist Financial' },
    { ticker: 'COF', name: 'Capital One' },
    { ticker: 'ICE', name: 'Intercontinental Exchange' },
    { ticker: 'CME', name: 'CME Group' },
    { ticker: 'AON', name: 'Aon plc' },
  ],
  energy: [
    { ticker: 'XOM', name: 'Exxon Mobil' },
    { ticker: 'CVX', name: 'Chevron' },
    { ticker: 'COP', name: 'ConocoPhillips' },
    { ticker: 'SLB', name: 'Schlumberger' },
    { ticker: 'EOG', name: 'EOG Resources' },
    { ticker: 'OXY', name: 'Occidental' },
    { ticker: 'PSX', name: 'Phillips 66' },
    { ticker: 'MPC', name: 'Marathon Petroleum' },
    { ticker: 'VLO', name: 'Valero Energy' },
    { ticker: 'HAL', name: 'Halliburton' },
    { ticker: 'WMB', name: 'Williams Companies' },
    { ticker: 'KMI', name: 'Kinder Morgan' },
    { ticker: 'OKE', name: 'ONEOK' },
    { ticker: 'DVN', name: 'Devon Energy' },
    { ticker: 'FANG', name: 'Diamondback Energy' },
    { ticker: 'BKR', name: 'Baker Hughes' },
    { ticker: 'HES', name: 'Hess Corporation' },
    { ticker: 'TRGP', name: 'Targa Resources' },
    { ticker: 'MRO', name: 'Marathon Oil' },
    { ticker: 'EPD', name: 'Enterprise Products' },
  ],
  consumer: [
    { ticker: 'WMT', name: 'Walmart' },
    { ticker: 'HD', name: 'Home Depot' },
    { ticker: 'COST', name: 'Costco' },
    { ticker: 'PG', name: 'Procter & Gamble' },
    { ticker: 'KO', name: 'Coca-Cola' },
    { ticker: 'PEP', name: 'PepsiCo' },
    { ticker: 'NKE', name: 'Nike Inc.' },
    { ticker: 'MCD', name: "McDonald's" },
    { ticker: 'SBUX', name: 'Starbucks' },
    { ticker: 'TGT', name: 'Target' },
    { ticker: 'LOW', name: "Lowe's" },
    { ticker: 'TJX', name: 'TJX Companies' },
    { ticker: 'CMG', name: 'Chipotle' },
    { ticker: 'BKNG', name: 'Booking Holdings' },
    { ticker: 'ORLY', name: "O'Reilly Auto" },
    { ticker: 'ROST', name: 'Ross Stores' },
    { ticker: 'DG', name: 'Dollar General' },
    { ticker: 'DLTR', name: 'Dollar Tree' },
    { ticker: 'YUM', name: 'Yum! Brands' },
    { ticker: 'MAR', name: 'Marriott' },
  ],
  industrial: [
    { ticker: 'CAT', name: 'Caterpillar' },
    { ticker: 'HON', name: 'Honeywell' },
    { ticker: 'UPS', name: 'UPS' },
    { ticker: 'BA', name: 'Boeing' },
    { ticker: 'GE', name: 'GE Aerospace' },
    { ticker: 'RTX', name: 'RTX Corporation' },
    { ticker: 'DE', name: 'Deere & Company' },
    { ticker: 'LMT', name: 'Lockheed Martin' },
    { ticker: 'UNP', name: 'Union Pacific' },
    { ticker: 'MMM', name: '3M Company' },
    { ticker: 'EMR', name: 'Emerson Electric' },
    { ticker: 'ITW', name: 'Illinois Tool Works' },
    { ticker: 'ETN', name: 'Eaton Corp' },
    { ticker: 'PH', name: 'Parker Hannifin' },
    { ticker: 'GD', name: 'General Dynamics' },
    { ticker: 'NSC', name: 'Norfolk Southern' },
    { ticker: 'CSX', name: 'CSX Corp' },
    { ticker: 'PCAR', name: 'PACCAR' },
    { ticker: 'WM', name: 'Waste Management' },
    { ticker: 'FDX', name: 'FedEx' },
  ],
};

export const SECTOR_NAMES = {
  tech: 'Technology',
  healthcare: 'Healthcare',
  finance: 'Finance',
  energy: 'Energy',
  consumer: 'Consumer',
  industrial: 'Industrial',
};
