// Ticker lists only. All stats (pe, eps, marketCap, beta) and prices (buy_price, sell_price)
// are fetched live from the /stats and /simulate lambda endpoints.
export const STOCKS_DATA = {
  tech: {
    2000: [
      { ticker: 'MSFT', name: 'Microsoft' },
      { ticker: 'INTC', name: 'Intel' },
      { ticker: 'CSCO', name: 'Cisco Systems' },
      { ticker: 'ORCL', name: 'Oracle' },
      { ticker: 'IBM', name: 'IBM' },
    ],
    2008: [
      { ticker: 'AAPL', name: 'Apple Inc.' },
      { ticker: 'MSFT', name: 'Microsoft' },
      { ticker: 'GOOGL', name: 'Alphabet' },
      { ticker: 'AMZN', name: 'Amazon' },
      { ticker: 'INTC', name: 'Intel' },
    ],
    2015: [
      { ticker: 'AAPL', name: 'Apple Inc.' },
      { ticker: 'MSFT', name: 'Microsoft' },
      { ticker: 'GOOGL', name: 'Alphabet' },
      { ticker: 'FB', name: 'Meta Platforms' },
      { ticker: 'AMZN', name: 'Amazon' },
    ],
    2020: [
      { ticker: 'AAPL', name: 'Apple Inc.' },
      { ticker: 'MSFT', name: 'Microsoft' },
      { ticker: 'NVDA', name: 'NVIDIA' },
      { ticker: 'GOOGL', name: 'Alphabet' },
      { ticker: 'META', name: 'Meta Platforms' },
    ],
    2023: [
      { ticker: 'AAPL', name: 'Apple Inc.' },
      { ticker: 'MSFT', name: 'Microsoft' },
      { ticker: 'NVDA', name: 'NVIDIA' },
      { ticker: 'GOOGL', name: 'Alphabet' },
      { ticker: 'META', name: 'Meta Platforms' },
    ],
    2024: [
      { ticker: 'AAPL', name: 'Apple Inc.' },
      { ticker: 'MSFT', name: 'Microsoft' },
      { ticker: 'NVDA', name: 'NVIDIA' },
      { ticker: 'GOOGL', name: 'Alphabet' },
      { ticker: 'META', name: 'Meta Platforms' },
    ],
  },
  healthcare: {
    2008: [
      { ticker: 'JNJ', name: 'Johnson & Johnson' },
      { ticker: 'PFE', name: 'Pfizer' },
      { ticker: 'MRK', name: 'Merck' },
      { ticker: 'AMGN', name: 'Amgen' },
      { ticker: 'GILD', name: 'Gilead Sciences' },
    ],
    2020: [
      { ticker: 'JNJ', name: 'Johnson & Johnson' },
      { ticker: 'UNH', name: 'UnitedHealth' },
      { ticker: 'PFE', name: 'Pfizer' },
      { ticker: 'ABBV', name: 'AbbVie' },
      { ticker: 'MRK', name: 'Merck' },
    ],
    2023: [
      { ticker: 'JNJ', name: 'Johnson & Johnson' },
      { ticker: 'UNH', name: 'UnitedHealth' },
      { ticker: 'PFE', name: 'Pfizer' },
      { ticker: 'ABBV', name: 'AbbVie' },
      { ticker: 'MRK', name: 'Merck' },
    ],
    2024: [
      { ticker: 'JNJ', name: 'Johnson & Johnson' },
      { ticker: 'UNH', name: 'UnitedHealth' },
      { ticker: 'PFE', name: 'Pfizer' },
      { ticker: 'ABBV', name: 'AbbVie' },
      { ticker: 'MRK', name: 'Merck' },
    ],
  },
  finance: {
    2008: [
      { ticker: 'JPM', name: 'JPMorgan Chase' },
      { ticker: 'BAC', name: 'Bank of America' },
      { ticker: 'WFC', name: 'Wells Fargo' },
      { ticker: 'C', name: 'Citigroup' },
      { ticker: 'GS', name: 'Goldman Sachs' },
    ],
    2020: [
      { ticker: 'JPM', name: 'JPMorgan Chase' },
      { ticker: 'BAC', name: 'Bank of America' },
      { ticker: 'V', name: 'Visa Inc.' },
      { ticker: 'MA', name: 'Mastercard' },
      { ticker: 'GS', name: 'Goldman Sachs' },
    ],
    2023: [
      { ticker: 'JPM', name: 'JPMorgan Chase' },
      { ticker: 'BAC', name: 'Bank of America' },
      { ticker: 'V', name: 'Visa Inc.' },
      { ticker: 'MA', name: 'Mastercard' },
      { ticker: 'GS', name: 'Goldman Sachs' },
    ],
    2024: [
      { ticker: 'JPM', name: 'JPMorgan Chase' },
      { ticker: 'BAC', name: 'Bank of America' },
      { ticker: 'V', name: 'Visa Inc.' },
      { ticker: 'MA', name: 'Mastercard' },
      { ticker: 'GS', name: 'Goldman Sachs' },
    ],
  },
  energy: {
    2008: [
      { ticker: 'XOM', name: 'Exxon Mobil' },
      { ticker: 'CVX', name: 'Chevron' },
      { ticker: 'COP', name: 'ConocoPhillips' },
      { ticker: 'SLB', name: 'Schlumberger' },
      { ticker: 'OXY', name: 'Occidental' },
    ],
    2020: [
      { ticker: 'XOM', name: 'Exxon Mobil' },
      { ticker: 'CVX', name: 'Chevron' },
      { ticker: 'COP', name: 'ConocoPhillips' },
      { ticker: 'NEE', name: 'NextEra Energy' },
      { ticker: 'SLB', name: 'Schlumberger' },
    ],
    2023: [
      { ticker: 'XOM', name: 'Exxon Mobil' },
      { ticker: 'CVX', name: 'Chevron' },
      { ticker: 'COP', name: 'ConocoPhillips' },
      { ticker: 'NEE', name: 'NextEra Energy' },
      { ticker: 'SLB', name: 'Schlumberger' },
    ],
    2024: [
      { ticker: 'XOM', name: 'Exxon Mobil' },
      { ticker: 'CVX', name: 'Chevron' },
      { ticker: 'COP', name: 'ConocoPhillips' },
      { ticker: 'NEE', name: 'NextEra Energy' },
      { ticker: 'SLB', name: 'Schlumberger' },
    ],
  },
  consumer: {
    2008: [
      { ticker: 'WMT', name: 'Walmart' },
      { ticker: 'PG', name: 'Procter & Gamble' },
      { ticker: 'KO', name: 'Coca-Cola' },
      { ticker: 'MCD', name: "McDonald's" },
      { ticker: 'NKE', name: 'Nike Inc.' },
    ],
    2020: [
      { ticker: 'AMZN', name: 'Amazon' },
      { ticker: 'WMT', name: 'Walmart' },
      { ticker: 'PG', name: 'Procter & Gamble' },
      { ticker: 'KO', name: 'Coca-Cola' },
      { ticker: 'NKE', name: 'Nike Inc.' },
    ],
    2023: [
      { ticker: 'AMZN', name: 'Amazon' },
      { ticker: 'WMT', name: 'Walmart' },
      { ticker: 'PG', name: 'Procter & Gamble' },
      { ticker: 'KO', name: 'Coca-Cola' },
      { ticker: 'NKE', name: 'Nike Inc.' },
    ],
    2024: [
      { ticker: 'AMZN', name: 'Amazon' },
      { ticker: 'WMT', name: 'Walmart' },
      { ticker: 'PG', name: 'Procter & Gamble' },
      { ticker: 'KO', name: 'Coca-Cola' },
      { ticker: 'NKE', name: 'Nike Inc.' },
    ],
  },
  industrial: {
    2008: [
      { ticker: 'GE', name: 'General Electric' },
      { ticker: 'CAT', name: 'Caterpillar' },
      { ticker: 'BA', name: 'Boeing' },
      { ticker: 'MMM', name: '3M Company' },
      { ticker: 'HON', name: 'Honeywell' },
    ],
    2020: [
      { ticker: 'CAT', name: 'Caterpillar' },
      { ticker: 'HON', name: 'Honeywell' },
      { ticker: 'UPS', name: 'UPS' },
      { ticker: 'BA', name: 'Boeing' },
      { ticker: 'GE', name: 'GE Aerospace' },
    ],
    2023: [
      { ticker: 'CAT', name: 'Caterpillar' },
      { ticker: 'HON', name: 'Honeywell' },
      { ticker: 'UPS', name: 'UPS' },
      { ticker: 'BA', name: 'Boeing' },
      { ticker: 'GE', name: 'GE Aerospace' },
    ],
    2024: [
      { ticker: 'CAT', name: 'Caterpillar' },
      { ticker: 'HON', name: 'Honeywell' },
      { ticker: 'UPS', name: 'UPS' },
      { ticker: 'BA', name: 'Boeing' },
      { ticker: 'GE', name: 'GE Aerospace' },
    ],
  },
};
